# Generated by Django 2.0 on 2018-03-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='dirección de correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designa si el usuario puede iniciar sesión en este sitio de administración.', verbose_name='estado del personal'),
        ),
    ]
